//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace CAMEL.Baking.TrayBindingWebService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="TrayBindingServiceSoap", Namespace="http://172.21.30.251/CamelPostSection/")]
    public partial class TrayBindingService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TrayBindingOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateTrayBindingDeviceIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrayUnbindingOperationCompleted;
        
        private System.Threading.SendOrPostCallback ProductUnbindingOperationCompleted;
        
        private System.Threading.SendOrPostCallback TrayBindingInfoDeletionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetTrayBindingInfoOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public TrayBindingService() {
            this.Url = global::CAMEL.Baking.Properties.Settings.Default.CAMEL_Baking_TrayBindingService_TrayBindingService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TrayBindingCompletedEventHandler TrayBindingCompleted;
        
        /// <remarks/>
        public event UpdateTrayBindingDeviceIdCompletedEventHandler UpdateTrayBindingDeviceIdCompleted;
        
        /// <remarks/>
        public event TrayUnbindingCompletedEventHandler TrayUnbindingCompleted;
        
        /// <remarks/>
        public event ProductUnbindingCompletedEventHandler ProductUnbindingCompleted;
        
        /// <remarks/>
        public event TrayBindingInfoDeletionCompletedEventHandler TrayBindingInfoDeletionCompleted;
        
        /// <remarks/>
        public event GetTrayBindingInfoCompletedEventHandler GetTrayBindingInfoCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/TrayBinding", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrayBinding(string xmlParams) {
            object[] results = this.Invoke("TrayBinding", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrayBindingAsync(string xmlParams) {
            this.TrayBindingAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void TrayBindingAsync(string xmlParams, object userState) {
            if ((this.TrayBindingOperationCompleted == null)) {
                this.TrayBindingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrayBindingOperationCompleted);
            }
            this.InvokeAsync("TrayBinding", new object[] {
                        xmlParams}, this.TrayBindingOperationCompleted, userState);
        }
        
        private void OnTrayBindingOperationCompleted(object arg) {
            if ((this.TrayBindingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrayBindingCompleted(this, new TrayBindingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/UpdateTrayBindingDeviceId", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateTrayBindingDeviceId(string xmlParams) {
            object[] results = this.Invoke("UpdateTrayBindingDeviceId", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateTrayBindingDeviceIdAsync(string xmlParams) {
            this.UpdateTrayBindingDeviceIdAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void UpdateTrayBindingDeviceIdAsync(string xmlParams, object userState) {
            if ((this.UpdateTrayBindingDeviceIdOperationCompleted == null)) {
                this.UpdateTrayBindingDeviceIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateTrayBindingDeviceIdOperationCompleted);
            }
            this.InvokeAsync("UpdateTrayBindingDeviceId", new object[] {
                        xmlParams}, this.UpdateTrayBindingDeviceIdOperationCompleted, userState);
        }
        
        private void OnUpdateTrayBindingDeviceIdOperationCompleted(object arg) {
            if ((this.UpdateTrayBindingDeviceIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateTrayBindingDeviceIdCompleted(this, new UpdateTrayBindingDeviceIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/TrayUnbinding", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrayUnbinding(string xmlParams) {
            object[] results = this.Invoke("TrayUnbinding", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrayUnbindingAsync(string xmlParams) {
            this.TrayUnbindingAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void TrayUnbindingAsync(string xmlParams, object userState) {
            if ((this.TrayUnbindingOperationCompleted == null)) {
                this.TrayUnbindingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrayUnbindingOperationCompleted);
            }
            this.InvokeAsync("TrayUnbinding", new object[] {
                        xmlParams}, this.TrayUnbindingOperationCompleted, userState);
        }
        
        private void OnTrayUnbindingOperationCompleted(object arg) {
            if ((this.TrayUnbindingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrayUnbindingCompleted(this, new TrayUnbindingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/ProductUnbinding", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string ProductUnbinding(string xmlParams) {
            object[] results = this.Invoke("ProductUnbinding", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ProductUnbindingAsync(string xmlParams) {
            this.ProductUnbindingAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void ProductUnbindingAsync(string xmlParams, object userState) {
            if ((this.ProductUnbindingOperationCompleted == null)) {
                this.ProductUnbindingOperationCompleted = new System.Threading.SendOrPostCallback(this.OnProductUnbindingOperationCompleted);
            }
            this.InvokeAsync("ProductUnbinding", new object[] {
                        xmlParams}, this.ProductUnbindingOperationCompleted, userState);
        }
        
        private void OnProductUnbindingOperationCompleted(object arg) {
            if ((this.ProductUnbindingCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ProductUnbindingCompleted(this, new ProductUnbindingCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/TrayBindingInfoDeletion", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string TrayBindingInfoDeletion(string xmlParams) {
            object[] results = this.Invoke("TrayBindingInfoDeletion", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TrayBindingInfoDeletionAsync(string xmlParams) {
            this.TrayBindingInfoDeletionAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void TrayBindingInfoDeletionAsync(string xmlParams, object userState) {
            if ((this.TrayBindingInfoDeletionOperationCompleted == null)) {
                this.TrayBindingInfoDeletionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTrayBindingInfoDeletionOperationCompleted);
            }
            this.InvokeAsync("TrayBindingInfoDeletion", new object[] {
                        xmlParams}, this.TrayBindingInfoDeletionOperationCompleted, userState);
        }
        
        private void OnTrayBindingInfoDeletionOperationCompleted(object arg) {
            if ((this.TrayBindingInfoDeletionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TrayBindingInfoDeletionCompleted(this, new TrayBindingInfoDeletionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://172.21.30.251/CamelPostSection/GetTrayBindingInfo", RequestNamespace="http://172.21.30.251/CamelPostSection/", ResponseNamespace="http://172.21.30.251/CamelPostSection/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetTrayBindingInfo(string xmlParams) {
            object[] results = this.Invoke("GetTrayBindingInfo", new object[] {
                        xmlParams});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetTrayBindingInfoAsync(string xmlParams) {
            this.GetTrayBindingInfoAsync(xmlParams, null);
        }
        
        /// <remarks/>
        public void GetTrayBindingInfoAsync(string xmlParams, object userState) {
            if ((this.GetTrayBindingInfoOperationCompleted == null)) {
                this.GetTrayBindingInfoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetTrayBindingInfoOperationCompleted);
            }
            this.InvokeAsync("GetTrayBindingInfo", new object[] {
                        xmlParams}, this.GetTrayBindingInfoOperationCompleted, userState);
        }
        
        private void OnGetTrayBindingInfoOperationCompleted(object arg) {
            if ((this.GetTrayBindingInfoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetTrayBindingInfoCompleted(this, new GetTrayBindingInfoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TrayBindingCompletedEventHandler(object sender, TrayBindingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrayBindingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrayBindingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void UpdateTrayBindingDeviceIdCompletedEventHandler(object sender, UpdateTrayBindingDeviceIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateTrayBindingDeviceIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateTrayBindingDeviceIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TrayUnbindingCompletedEventHandler(object sender, TrayUnbindingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrayUnbindingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrayUnbindingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void ProductUnbindingCompletedEventHandler(object sender, ProductUnbindingCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ProductUnbindingCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ProductUnbindingCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void TrayBindingInfoDeletionCompletedEventHandler(object sender, TrayBindingInfoDeletionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TrayBindingInfoDeletionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TrayBindingInfoDeletionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    public delegate void GetTrayBindingInfoCompletedEventHandler(object sender, GetTrayBindingInfoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3761.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetTrayBindingInfoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetTrayBindingInfoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591