//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.42000 版自动生成。
// 
#pragma warning disable 1591

namespace BYD.Mes.Test.MesService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AutoLineServiceSoap", Namespace="http://tempuri.org/")]
    public partial class AutoLineService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private MySoapHelper mySoapHelperValueField;
        
        private System.Threading.SendOrPostCallback FetchParameterOperationCompleted;
        
        private System.Threading.SendOrPostCallback FetchForeWeightOperationCompleted;
        
        private System.Threading.SendOrPostCallback PackAsbValidateOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoltVersionOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetBoltStandardOperationCompleted;
        
        private System.Threading.SendOrPostCallback PassStationCheckOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AutoLineService() {
            this.Url = global::BYD.Mes.Test.Properties.Settings.Default.BYD_Mes_Test_MesService_AutoLineService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public MySoapHelper MySoapHelperValue {
            get {
                return this.mySoapHelperValueField;
            }
            set {
                this.mySoapHelperValueField = value;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event FetchParameterCompletedEventHandler FetchParameterCompleted;
        
        /// <remarks/>
        public event FetchForeWeightCompletedEventHandler FetchForeWeightCompleted;
        
        /// <remarks/>
        public event PackAsbValidateCompletedEventHandler PackAsbValidateCompleted;
        
        /// <remarks/>
        public event GetBoltVersionCompletedEventHandler GetBoltVersionCompleted;
        
        /// <remarks/>
        public event GetBoltStandardCompletedEventHandler GetBoltStandardCompleted;
        
        /// <remarks/>
        public event PassStationCheckCompletedEventHandler PassStationCheckCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchParameter", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FetchParameter(int typeCode, string midModel) {
            object[] results = this.Invoke("FetchParameter", new object[] {
                        typeCode,
                        midModel});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FetchParameterAsync(int typeCode, string midModel) {
            this.FetchParameterAsync(typeCode, midModel, null);
        }
        
        /// <remarks/>
        public void FetchParameterAsync(int typeCode, string midModel, object userState) {
            if ((this.FetchParameterOperationCompleted == null)) {
                this.FetchParameterOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchParameterOperationCompleted);
            }
            this.InvokeAsync("FetchParameter", new object[] {
                        typeCode,
                        midModel}, this.FetchParameterOperationCompleted, userState);
        }
        
        private void OnFetchParameterOperationCompleted(object arg) {
            if ((this.FetchParameterCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchParameterCompleted(this, new FetchParameterCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/FetchForeWeight", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string FetchForeWeight(string cellBarcode) {
            object[] results = this.Invoke("FetchForeWeight", new object[] {
                        cellBarcode});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void FetchForeWeightAsync(string cellBarcode) {
            this.FetchForeWeightAsync(cellBarcode, null);
        }
        
        /// <remarks/>
        public void FetchForeWeightAsync(string cellBarcode, object userState) {
            if ((this.FetchForeWeightOperationCompleted == null)) {
                this.FetchForeWeightOperationCompleted = new System.Threading.SendOrPostCallback(this.OnFetchForeWeightOperationCompleted);
            }
            this.InvokeAsync("FetchForeWeight", new object[] {
                        cellBarcode}, this.FetchForeWeightOperationCompleted, userState);
        }
        
        private void OnFetchForeWeightOperationCompleted(object arg) {
            if ((this.FetchForeWeightCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.FetchForeWeightCompleted(this, new FetchForeWeightCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PackAsbValidate", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PackAsbValidate(string moduleBarcodes) {
            object[] results = this.Invoke("PackAsbValidate", new object[] {
                        moduleBarcodes});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PackAsbValidateAsync(string moduleBarcodes) {
            this.PackAsbValidateAsync(moduleBarcodes, null);
        }
        
        /// <remarks/>
        public void PackAsbValidateAsync(string moduleBarcodes, object userState) {
            if ((this.PackAsbValidateOperationCompleted == null)) {
                this.PackAsbValidateOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPackAsbValidateOperationCompleted);
            }
            this.InvokeAsync("PackAsbValidate", new object[] {
                        moduleBarcodes}, this.PackAsbValidateOperationCompleted, userState);
        }
        
        private void OnPackAsbValidateOperationCompleted(object arg) {
            if ((this.PackAsbValidateCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PackAsbValidateCompleted(this, new PackAsbValidateCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBoltVersion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBoltVersion(string modelId) {
            object[] results = this.Invoke("GetBoltVersion", new object[] {
                        modelId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoltVersionAsync(string modelId) {
            this.GetBoltVersionAsync(modelId, null);
        }
        
        /// <remarks/>
        public void GetBoltVersionAsync(string modelId, object userState) {
            if ((this.GetBoltVersionOperationCompleted == null)) {
                this.GetBoltVersionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoltVersionOperationCompleted);
            }
            this.InvokeAsync("GetBoltVersion", new object[] {
                        modelId}, this.GetBoltVersionOperationCompleted, userState);
        }
        
        private void OnGetBoltVersionOperationCompleted(object arg) {
            if ((this.GetBoltVersionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoltVersionCompleted(this, new GetBoltVersionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/GetBoltStandard", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string GetBoltStandard(string modelId) {
            object[] results = this.Invoke("GetBoltStandard", new object[] {
                        modelId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void GetBoltStandardAsync(string modelId) {
            this.GetBoltStandardAsync(modelId, null);
        }
        
        /// <remarks/>
        public void GetBoltStandardAsync(string modelId, object userState) {
            if ((this.GetBoltStandardOperationCompleted == null)) {
                this.GetBoltStandardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetBoltStandardOperationCompleted);
            }
            this.InvokeAsync("GetBoltStandard", new object[] {
                        modelId}, this.GetBoltStandardOperationCompleted, userState);
        }
        
        private void OnGetBoltStandardOperationCompleted(object arg) {
            if ((this.GetBoltStandardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetBoltStandardCompleted(this, new GetBoltStandardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapHeaderAttribute("MySoapHelperValue")]
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/PassStationCheck", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string PassStationCheck(string barcode, string flag, string terminal, string userId) {
            object[] results = this.Invoke("PassStationCheck", new object[] {
                        barcode,
                        flag,
                        terminal,
                        userId});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void PassStationCheckAsync(string barcode, string flag, string terminal, string userId) {
            this.PassStationCheckAsync(barcode, flag, terminal, userId, null);
        }
        
        /// <remarks/>
        public void PassStationCheckAsync(string barcode, string flag, string terminal, string userId, object userState) {
            if ((this.PassStationCheckOperationCompleted == null)) {
                this.PassStationCheckOperationCompleted = new System.Threading.SendOrPostCallback(this.OnPassStationCheckOperationCompleted);
            }
            this.InvokeAsync("PassStationCheck", new object[] {
                        barcode,
                        flag,
                        terminal,
                        userId}, this.PassStationCheckOperationCompleted, userState);
        }
        
        private void OnPassStationCheckOperationCompleted(object arg) {
            if ((this.PassStationCheckCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.PassStationCheckCompleted(this, new PassStationCheckCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3190.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="http://tempuri.org/", IsNullable=false)]
    public partial class MySoapHelper : System.Web.Services.Protocols.SoapHeader {
        
        private string userNameField;
        
        private string passWordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        public string userName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        public string passWord {
            get {
                return this.passWordField;
            }
            set {
                this.passWordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FetchParameterCompletedEventHandler(object sender, FetchParameterCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchParameterCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchParameterCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void FetchForeWeightCompletedEventHandler(object sender, FetchForeWeightCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class FetchForeWeightCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal FetchForeWeightCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PackAsbValidateCompletedEventHandler(object sender, PackAsbValidateCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PackAsbValidateCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PackAsbValidateCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetBoltVersionCompletedEventHandler(object sender, GetBoltVersionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoltVersionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoltVersionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void GetBoltStandardCompletedEventHandler(object sender, GetBoltStandardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetBoltStandardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetBoltStandardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    public delegate void PassStationCheckCompletedEventHandler(object sender, PassStationCheckCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3190.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class PassStationCheckCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal PassStationCheckCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591